# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'StdIt' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for StdIt

  target 'StdItTests' do
    pod 'SwiftyJSON'
    pod 'Charts'
    inherit! :search_paths
    # Pods for testing
  end

end
